name: bind9-docker-ddns

services:
  bind9-docker-ddns:
    build:
      context: .
    image: bind9-docker-ddns
    container_name: bind9-docker-ddns
    hostname: ns.docker.snigji.com
    labels:
      bind9-docker-ddns.docker.snigji.com.hostname: ns
    environment:
      trusted_cidrs: "192.168.73.0/24,192.168.74.0/24,192.168.75.0/24,192.168.200.0/24"
      dns_forwarders: "9.9.9.9,1.1.1.1,8.8.8.8"
      zone: "docker.snigji.com"
      reverse_zone: "168.192.in-addr.arpa"
      nameserver_hostname: "ns"
      static_records: | # syntax=yaml
        docker.snigji.com:
          adhir: A,192.168.73.10
          ketaki: A,192.168.73.12
          alexa: A,192.168.73.14
          pi5: A,192.168.73.100
          pc: A,192.168.73.101
          phone: A,192.168.73.104
          ipad: A,192.168.73.105
          m1: A,192.168.73.200
    ports:
      - "8053:53"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - bind_home:/etc/bind
#      - bind_cache:/var/cache/bind
#      - bind_record:/var/lib/bind

  test1:
    image: alpine
    container_name: test1
    labels:
      bind9-docker-ddns.docker.snigji.com.hostname: test1
      bind9-docker-ddns.docker.snigji.com.record-type: CNAME
      bind9-docker-ddns.docker.snigji.com.record-value: test2
      bind9-docker-ddns.docker.snigji.com.docker-network: bind9-docker-ddns
    entrypoint: ["sleep", "infinity"]

  test2:
    image: alpine
    container_name: debug
    labels:
      bind9-docker-ddns.docker.snigji.com.hostname: test2
    entrypoint: ["sleep", "infinity"]

volumes:
  bind_home:
    name: bind_home
  bind_cache:
    name: bind_cache
  bind_record:
    name: bind_record

networks:
  default:
    name: bind9-docker-ddns
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.200.0/24"
          gateway: "192.168.200.1"